// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Author is the predicate function for author builders.
type Author func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Like is the predicate function for like builders.
type Like func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)
